version: '3.4'
services:
  fritakagp-database:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
#
#  fritakagp-kafka:
#    build:
#      context: ./kafka
#      dockerfile: kafka.Dockerfile
#    ports:
#      - "2181:2181"
#      - "9092:9092"
#
#volumes:
#  data: