context: dev
bucketName: helse-arbeidsgiver-fritakagb-bucket
ingresses:
  - https://fritakagp-api.intern.dev.nav.no
accessOutbound:
  apps:
    - name: notifikasjon-produsent-api
      namespace: fager
  external:
    - kafka-schema-registry.nais-q.adeo.no
    - dokarkiv.dev-fss-pub.nais.io
    - helsearbeidsgiver-proxy.dev-fss-pub.nais.io
    - pdl-api.dev-fss-pub.nais.io
    - oppgave-q1.dev-fss-pub.nais.io
    - api-gw-q1.oera.no
    - tt02.altinn.no
    - data.brreg.no
    - g.nav.no
    - test.idporten.no
envFrom:
  # servicebrukerens passord som er  hentet fra vault og lagt inn slik: https://doc.nais.io/security/secrets/kubernetes-secrets/
  - service-user-password
  - altinn-user-password
  - altinn-api-gw-keys
env:
  - name: KOIN_PROFILE
    value: PREPROD
  - name: KTOR_APPLICATION_BASEPATH
    value: /fritak-agp-api
  - name: GCP_PRJ_ID
    value: helsearbeidsgiver-dev-6d06
  - name: GCP_BUCKET_NAME
    value: helse-arbeidsgiver-fritakagb-bucket
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: api://dev-gcp.fager.notifikasjon-produsent-api/.default
  - name: DOKARKIV_SCOPE
    value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
  - name: OPPGAVE_SCOPE
    value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
  - name: PDL_SCOPE
    value: api://dev-fss.pdl.pdl-api/.default
  - name: PROXY_SCOPE
    value: api://dev-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default
  - name: FRONTEND_URL
    value: https://arbeidsgiver.intern.dev.nav.no/fritak-agp
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: http://notifikasjon-produsent-api.fager/api/graphql
  - name: DOKARKIV_URL
    value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1
  - name: GRUNNBELOEP_URL
    value: https://g.nav.no/api/v1/grunnbel√∏p
  - name: NORG2_URL
    value: https://helsearbeidsgiver-proxy.dev-fss-pub.nais.io/norg
  - name: OPPGAVEBEHANDLING_URL
    value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
  - name: PDL_URL
    value: https://pdl-api.dev-fss-pub.nais.io/graphql
  - name: ALTINN_SERVICE_OWNER_GW_URL
    value: https://api-gw-q1.oera.no/ekstern/altinn/api/serviceowner
  - name: ALTINN_ENDPOINT
    value: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
  - name: ENHETSREGISTERET
    value: https://data.brreg.no/enhetsregisteret/api/underenheter
