apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fritakagp
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 2
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://fritakagp.dev.nav.no
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 3500m
      memory: 1000Mi
    requests:
      cpu: 400m
      memory: 200Mi
  leaderElection: false
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      external:
        - host: helsearbeidsgiver-proxy.dev-fss-pub.nais.io
        - host: tt02.altinn.no
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: data.brreg.no

      rules:
        - application: helsearbeidsgiver-proxy
          namespace: helsearbeidsgiver
          cluster: dev-fss

  envFrom:
    # servicebrukerens passord som er  hentet fra vault og lagt inn slik: https://doc.nais.io/security/secrets/kubernetes-secrets/
    - secret: service-user-password
    - secret: altinn-user-password
    - secret: altinn-api-gw-keys
    #- configmap: loginservice-idporten # tilgjengeliggj√∏r LOGINSERVICE_IDPORTEN_DISCOVERY_URL og LOGINSERVICE_IDPORTEN_AUDIENCE
    # Skrur av ^^^ i PREPROD siden loginservice ikke virker via naisdevice
  env:
    - name: KOIN_PROFILE
      value: PREPROD
    - name: DOKARKIV_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/dokarkiv
    - name: OPPGAVEBEHANDLING_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/oppgave
    - name: PDL_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/pdl
    - name: ALTINN_ENDPOINT
      value: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
    - name: CLAM_AV_URL
      value: http://clamav.clamav.svc.cluster.local/scan
    - name: GCP_PRJ_ID
      value: helsearbeidsgiver-dev-6d06
    - name: GCP_BUCKET_NAME
      value: helse-arbeidsgiver-fritakagb-bucket
    - name: ALTINN_SERVICE_OWNER_GW_URL
      value: https://api-gw-q1.oera.no/ekstern/altinn/api/serviceowner
    - name: ENHETSREGISTERET
      value: data.brreg.no/enhetsregisteret/api/underenheter
    - name: AVRO_SCHEMA_SERVER_URL
      value: https://kafka-schema-registry.nais-q.adeo.no
    - name: ON_PREM_KAFKA_BROKERS
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_BESKJED_TOPIC_NAME
      value: aapen-brukernotifikasjon-nyBeskjed-v1
    - name: PROXY_SCOPE
      value: api://dev-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: fritakagp-db
            diskAutoresize: true
    buckets:
      - name: helse-arbeidsgiver-fritakagb-bucket
        #retentionPeriodDays: 30
         # lifecycleCondition:
         # age: 7
         # createdBefore: 2020-01-01
         # numNewerVersions: 2
        #  withState: ANY

  kafka:
    pool: nav-dev    # enum of nav-dev, nav-prod
