context: prod
bucketName: helse-arbeidsgiver-fritakagb-bucket-prod
dbTier: db-custom-1-3840
ingresses:
  - https://fritakagp-api.intern.nav.no
accessOutbound:
  apps:
    - name: notifikasjon-produsent-api
      namespace: fager
    - name: arbeidsgiver-altinn-tilganger
      namespace: fager
  external:
    - kafka-schema-registry.nais.adeo.no
    - dokarkiv.prod-fss-pub.nais.io
    - pdl-api.prod-fss-pub.nais.io
    - aareg-services.prod-fss-pub.nais.io
    - oppgave.prod-fss-pub.nais.io
    - ag-notifikasjon-produsent-api.intern.nav.no
    - api-gw.oera.no
    - www.altinn.no
    - data.brreg.no
    - g.nav.no
accessInbound:
  apps:
    - name: fritak-agp-frontend
      namespace: helsearbeidsgiver
envFrom:
  # servicebrukerens passord som er  hentet fra vault og lagt inn slik: https://doc.nais.io/security/secrets/kubernetes-secrets/
  - service-user-password-prod
  - altinn-user-password-prod
  - altinn-api-gw-keys-prod
env:
  - name: KOIN_PROFILE
    value: PROD
  - name: KTOR_APPLICATION_BASEPATH
    value: /fritak-agp-api
  - name: GCP_PRJ_ID
    value: helsearbeidsgiver-prod-8a1c
  - name: GCP_BUCKET_NAME
    value: helse-arbeidsgiver-fritakagb-bucket-prod
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: api://prod-gcp.fager.notifikasjon-produsent-api/.default
  - name: DOKARKIV_SCOPE
    value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
  - name: OPPGAVE_SCOPE
    value: api://prod-fss.oppgavehandtering.oppgave/.default
  - name: PDL_SCOPE
    value: api://prod-fss.pdl.pdl-api/.default
  - name: AAREG_SCOPE
    value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default
  - name: FRONTEND_URL
    value: https://arbeidsgiver.nav.no/fritak-agp
  - name: AAREG_URL
    value: https://aareg-services.prod-fss-pub.nais.io/api/v1/arbeidstaker/arbeidsforhold?sporingsinformasjon=false&historikk=false
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: https://ag-notifikasjon-produsent-api.intern.nav.no/api/graphql
  - name: DOKARKIV_URL
    value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1
  - name: GRUNNBELOEP_URL
    value: https://g.nav.no/api/v1/grunnbel√∏p
  - name: OPPGAVEBEHANDLING_URL
    value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
  - name: PDL_URL
    value: https://pdl-api.prod-fss-pub.nais.io/graphql
  - name: ALTINN_SERVICE_OWNER_URL
    value: https://altinn.no/api/serviceowner
  - name: ALTINN_ENDPOINT
    value: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
  - name: ALTINN_SCOPE
    value: altinn:serviceowner/reportees
  - name: ENHETSREGISTERET
    value: https://data.brreg.no/enhetsregisteret/api/underenheter
  - name: ALTINN_TILGANGER_SCOPE
    value: prod-gcp:fager:arbeidsgiver-altinn-tilganger
  - name: ALTINN_TILGANGER_BASE_URL
    value: http://arbeidsgiver-altinn-tilganger.fager
maskinporten:
  consumes:
    - "altinn:serviceowner/reportees"
